CREATE TABLE IF NOT EXISTS "ai_chat_requests" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "client_message_id" VARCHAR(128) NOT NULL,
    "phase" VARCHAR(32) NOT NULL,
    "model_used" VARCHAR(100),
    "assistant_message_id" BIGINT,
    "error_message" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ai_chat_requests_session_client UNIQUE ("session_id", "client_message_id")
);


DO $$ BEGIN
    IF NOT EXISTS (
        SELECT
            1
        FROM
            pg_constraint
        WHERE
            conname = 'fk_ai_chat_requests_session'
    ) THEN
    ALTER TABLE
        "ai_chat_requests"
    ADD
        CONSTRAINT fk_ai_chat_requests_session FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") ON
    DELETE
        CASCADE;


END IF;


END $$;


DO $$ BEGIN
    IF NOT EXISTS (
        SELECT
            1
        FROM
            pg_constraint
        WHERE
            conname = 'fk_ai_chat_requests_assistant_message'
    ) THEN
    ALTER TABLE
        "ai_chat_requests"
    ADD
        CONSTRAINT fk_ai_chat_requests_assistant_message FOREIGN KEY ("assistant_message_id") REFERENCES "chat_messages" ("id") ON
    DELETE
    SET
        NULL;


END IF;


END $$;


CREATE INDEX IF NOT EXISTS idx_ai_chat_requests_session_updated ON "ai_chat_requests" ("session_id", "updated_at" DESC);


CREATE INDEX IF NOT EXISTS idx_ai_chat_requests_user_updated ON "ai_chat_requests" ("user_id", "updated_at" DESC);


COMMENT ON TABLE "ai_chat_requests" IS 'Tracks per-message AI stream processing phases for polling UX';


COMMENT ON COLUMN "ai_chat_requests"."phase" IS 'QUEUED, ROUTING, THINKING, GENERATING, FINALIZED, FAILED';