-- V14__skills_labels_schema.sql

-- Required skills as normalized relation (projects owns IDs only)
CREATE TABLE task_required_skills (
    task_id  BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, skill_id),
    CONSTRAINT fk_trs_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
    -- Note: no FK to skills table from this migration — cross-module boundary respected at JPA level
);

-- Project-scoped labels
CREATE TABLE labels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name       VARCHAR(100) NOT NULL,
    color      VARCHAR(7) DEFAULT '#6366F1',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_label_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT uq_label_project_name UNIQUE (project_id, name)
);

-- Task ↔ Label join table
CREATE TABLE task_labels (
    task_id  BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, label_id),
    CONSTRAINT fk_tl_task  FOREIGN KEY (task_id)  REFERENCES tasks(id)  ON DELETE CASCADE,
    CONSTRAINT fk_tl_label FOREIGN KEY (label_id) REFERENCES labels(id) ON DELETE CASCADE
);

COMMENT ON TABLE task_required_skills IS 'Projects module owns task_id + skill_id. Skill data fetched via SkillPort.';
COMMENT ON TABLE labels IS 'Project-scoped labels. Created inline by project members.';
