
CREATE TYPE "system_role" AS ENUM ('ADMIN', 'USER');
CREATE TYPE "user_status" AS ENUM ('AVAILABLE', 'BUSY', 'OOO');
CREATE TYPE "project_status" AS ENUM ('PLANNING', 'ACTIVE', 'COMPLETED', 'ARCHIVED');
CREATE TYPE "project_role" AS ENUM ('MANAGER', 'MEMBER');
CREATE TYPE "sprint_status" AS ENUM ('PLANNING', 'ACTIVE', 'COMPLETED');
CREATE TYPE "task_status" AS ENUM ('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE');
CREATE TYPE "priority_level" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "chat_sender" AS ENUM ('USER', 'ASSISTANT', 'SYSTEM');
CREATE TYPE "notification_type" AS ENUM ('SYSTEM', 'ASSIGNED', 'DEADLINE_NEAR');

-- ------------------------------------------

CREATE TABLE "system_settings"
(
    "key_name"    VARCHAR PRIMARY KEY,
    "value_json"  JSONB NOT NULL,
    "description" TEXT
);

CREATE TABLE "users"
(
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"            VARCHAR UNIQUE NOT NULL,
    "full_name"        VARCHAR        NOT NULL,
    "password_hash"    VARCHAR        NOT NULL,
    "avatar_url"       TEXT,
    "role"             system_role              DEFAULT 'USER',
    "status"           user_status              DEFAULT 'AVAILABLE',
    "current_workload" INT                      DEFAULT 0,
    "created_at"       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "skills"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "user_skills"
(
    "user_id"  BIGINT,
    "skill_id" BIGINT,
    "level"    INT,
    PRIMARY KEY ("user_id", "skill_id")
);

CREATE TABLE "projects"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        VARCHAR NOT NULL,
    "description" TEXT,
    "status"      project_status           DEFAULT 'ACTIVE',
    "start_date"  DATE,
    "end_date"    DATE,
    "created_at"  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "project_members"
(
    "project_id" BIGINT,
    "user_id"    BIGINT,
    "role"       project_role             DEFAULT 'MEMBER',
    "joined_at"  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("project_id", "user_id")
);

CREATE TABLE "sprints"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" BIGINT,
    "name"       VARCHAR NOT NULL,
    "goal"       TEXT,
    "status"     sprint_status DEFAULT 'PLANNING',
    "start_date" DATE,
    "end_date"   DATE
);

CREATE TABLE "tasks"
(
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"       BIGINT,
    "parent_id"        BIGINT,
    "sprint_id"        BIGINT,
    "title"            VARCHAR NOT NULL,
    "description"      TEXT,
    "status"           task_status              DEFAULT 'TODO',
    "priority"         priority_level           DEFAULT 'MEDIUM',
    "position"         FLOAT                    DEFAULT 0,
    "tags"             TEXT[],
    "difficulty_level" INT                      DEFAULT 1,
    "required_skills"  JSONB,
    "assignee_id"      BIGINT,
    "reporter_id"      BIGINT,
    "start_date"       TIMESTAMP WITH TIME ZONE,
    "due_date"         TIMESTAMP WITH TIME ZONE,
    "created_at"       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "comments"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_id"    BIGINT,
    "user_id"    BIGINT,
    "content"    TEXT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "notifications"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"     BIGINT,
    "title"       VARCHAR NOT NULL,
    "message"     TEXT,
    "type"        notification_type,
    "is_read"     BOOLEAN                  DEFAULT false,
    "link_action" VARCHAR,
    "created_at"  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "chat_sessions"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"    BIGINT,
    "title"      VARCHAR,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "chat_messages"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" BIGINT,
    "sender"     chat_sender NOT NULL,
    "content"    TEXT        NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ai_logs"
(
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"      BIGINT,
    "user_id"         BIGINT,
    "chat_message_id" BIGINT,
    "request"         TEXT,
    "response"        TEXT,
    "reasoning"       TEXT,
    "action_taken"    VARCHAR,
    "tool_output"     JSONB,
    "human_feedback"  VARCHAR                  DEFAULT 'PENDING',
    "created_at"      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------

ALTER TABLE "user_skills"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "user_skills"
    ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON DELETE CASCADE;

ALTER TABLE "project_members"
    ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "project_members"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "sprints"
    ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;

ALTER TABLE "tasks"
    ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "tasks"
    ADD FOREIGN KEY ("parent_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "tasks"
    ADD FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id") ON DELETE SET NULL;
ALTER TABLE "tasks"
    ADD FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "tasks"
    ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "comments"
    ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
ALTER TABLE "comments"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "notifications"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "chat_sessions"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "chat_messages"
    ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") ON DELETE CASCADE;

ALTER TABLE "ai_logs"
    ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE;
ALTER TABLE "ai_logs"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "ai_logs"
    ADD FOREIGN KEY ("chat_message_id") REFERENCES "chat_messages" ("id") ON DELETE SET NULL;

-- ------------------------------------------

COMMENT
ON COLUMN "system_settings"."key_name" IS 'Vd: heuristic.weights';
COMMENT
ON COLUMN "system_settings"."value_json" IS 'Lưu trọng số thuật toán';

COMMENT
ON COLUMN "users"."current_workload" IS 'Tổng độ khó task đang làm';
COMMENT
ON COLUMN "user_skills"."level" IS 'Scale 1-5';

COMMENT
ON COLUMN "sprints"."goal" IS 'Context cung cấp cho AI để đánh giá tiến độ';

COMMENT
ON COLUMN "tasks"."parent_id" IS 'Subtask Logic (Dùng cho Use-case 47)';
COMMENT
ON COLUMN "tasks"."position" IS 'Dùng để sort Kanban Board (Kéo thả)';
COMMENT
ON COLUMN "tasks"."tags" IS 'Postgres Array: vd ["Bug", "Urgent"]';
COMMENT
ON COLUMN "tasks"."difficulty_level" IS 'Heuristic Input: Thang điểm 1-10';
COMMENT
ON COLUMN "tasks"."required_skills" IS 'AI Matching: vd ["Java", "AWS"]';

COMMENT
ON COLUMN "ai_logs"."request" IS 'Câu hỏi/Prompt gốc của User';
COMMENT
ON COLUMN "ai_logs"."response" IS 'Câu trả lời cuối cùng của AI';
COMMENT
ON COLUMN "ai_logs"."reasoning" IS 'Chain of Thought (CoT) - Luồng suy nghĩ của AI';
COMMENT
ON COLUMN "ai_logs"."action_taken" IS 'Function Calling Name (Tên hàm AI đã gọi)';
COMMENT
ON COLUMN "ai_logs"."tool_output" IS 'Kết quả trả về từ Tool/Heuristic (Vd: {"score": 9.5})';
COMMENT
ON COLUMN "ai_logs"."human_feedback" IS 'Trạng thái đánh giá: PENDING, ACCEPTED, REJECTED';