CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "documents" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"        BIGINT NOT NULL,
    "storage_key"       VARCHAR(512) NOT NULL,
    "original_filename" VARCHAR(255) NOT NULL,
    "content_type"      VARCHAR(100),
    "file_size"         BIGINT,
    "status"            VARCHAR(32) NOT NULL DEFAULT 'UPLOADING',
    "error_message"     TEXT,
    "created_by"        BIGINT,
    "created_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_documents_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_documents_user" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "document_chunks" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "document_id"       BIGINT NOT NULL,
    "project_id"        BIGINT NOT NULL,
    "chunk_index"       INT NOT NULL,
    "content"           TEXT NOT NULL,
    "embedding"         vector(768) NOT NULL,
    "created_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_document_chunks_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_document_chunks_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_documents_project_id" ON "documents"("project_id");
CREATE INDEX IF NOT EXISTS "idx_documents_status" ON "documents"("status");
CREATE INDEX IF NOT EXISTS "idx_document_chunks_project_id" ON "document_chunks"("project_id");
CREATE INDEX IF NOT EXISTS "idx_document_chunks_document_id" ON "document_chunks"("document_id");

CREATE INDEX IF NOT EXISTS "idx_document_chunks_embedding_hnsw"
ON "document_chunks"
USING hnsw ("embedding" vector_cosine_ops)
WITH (m = 16, ef_construction = 64);
