-- V27: Create document chunk staging table for resumable RAG ingestion
CREATE TABLE IF NOT EXISTS "document_chunk_staging" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "document_id"        BIGINT NOT NULL,
    "processing_version" INT NOT NULL,
    "chunk_index"        INT NOT NULL,
    "content"            TEXT NOT NULL,
    "embedding"          vector(768) NULL,
    "created_at"         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_staging_document" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE,
    CONSTRAINT "uq_document_chunk_staging" UNIQUE ("document_id", "processing_version", "chunk_index")
);

CREATE INDEX IF NOT EXISTS "idx_staging_unembedded"
ON "document_chunk_staging" ("document_id", "processing_version", "chunk_index")
WHERE "embedding" IS NULL;

CREATE INDEX IF NOT EXISTS "idx_staging_doc_version"
ON "document_chunk_staging" ("document_id", "processing_version");
