CREATE TABLE IF NOT EXISTS "project_files" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"        BIGINT NOT NULL,
    "uploader_id"       BIGINT,
    "file_name"         VARCHAR(255) NOT NULL,
    "original_name"     VARCHAR(255) NOT NULL,
    "file_size"         BIGINT NOT NULL,
    "content_type"      VARCHAR(100),
    "storage_key"       VARCHAR(512) NOT NULL,
    "storage_bucket"    VARCHAR(100) NOT NULL DEFAULT 'documents',
    "description"       TEXT,
    "created_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_project_files_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_project_files_uploader" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "project_chat_messages" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"        BIGINT NOT NULL,
    "sender_id"         BIGINT NOT NULL,
    "content"           TEXT NOT NULL,
    "message_type"      VARCHAR(32) NOT NULL DEFAULT 'TEXT',
    "file_id"           BIGINT,
    "created_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_project_chat_messages_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_project_chat_messages_sender" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_project_chat_messages_file" FOREIGN KEY ("file_id") REFERENCES "project_files"("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "idx_project_files_project_id" ON "project_files"("project_id");
CREATE INDEX IF NOT EXISTS "idx_project_files_uploader_id" ON "project_files"("uploader_id");
CREATE INDEX IF NOT EXISTS "idx_project_chat_messages_project_id" ON "project_chat_messages"("project_id");
CREATE INDEX IF NOT EXISTS "idx_project_chat_messages_created_at" ON "project_chat_messages"("created_at");
