CREATE TABLE IF NOT EXISTS "project_meetings" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id"        BIGINT NOT NULL,
    "host_id"           BIGINT,
    "title"             VARCHAR(255) NOT NULL,
    "description"       TEXT,
    "room_name"         VARCHAR(255) NOT NULL UNIQUE,
    "status"            VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    "recording_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "recording_file_id" BIGINT,
    "started_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "ended_at"          TIMESTAMP WITH TIME ZONE,
    "created_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_project_meetings_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_project_meetings_host" FOREIGN KEY ("host_id") REFERENCES "users"("id") ON DELETE SET NULL,
    CONSTRAINT "fk_project_meetings_recording" FOREIGN KEY ("recording_file_id") REFERENCES "project_files"("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "project_meeting_participants" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "meeting_id"        BIGINT NOT NULL,
    "user_id"           BIGINT NOT NULL,
    "role"              VARCHAR(32) NOT NULL DEFAULT 'PARTICIPANT',
    "joined_at"         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "left_at"           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT "fk_project_meeting_participants_meeting" FOREIGN KEY ("meeting_id") REFERENCES "project_meetings"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_project_meeting_participants_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_project_meetings_project_id" ON "project_meetings"("project_id");
CREATE INDEX IF NOT EXISTS "idx_project_meetings_status" ON "project_meetings"("status");
CREATE INDEX IF NOT EXISTS "idx_project_meetings_room_name" ON "project_meetings"("room_name");
CREATE INDEX IF NOT EXISTS "idx_project_meeting_participants_meeting_id" ON "project_meeting_participants"("meeting_id");
CREATE INDEX IF NOT EXISTS "idx_project_meeting_participants_user_id" ON "project_meeting_participants"("user_id");
