-- V34__create_recommendation_snapshots_tables.sql
-- Append-only recommendation snapshots and candidate evidence for Phase 2A

CREATE TABLE IF NOT EXISTS "recommendation_snapshots" (
    "snapshot_id"                   VARCHAR(64) PRIMARY KEY,
    "requested_by_user_id"          BIGINT NOT NULL,
    "project_id"                    BIGINT NOT NULL,
    "task_id"                       BIGINT,
    "created_at"                    TIMESTAMP WITH TIME ZONE NOT NULL,
    "heuristic_mode"                VARCHAR(32) NOT NULL,
    "presentation_contract_version" VARCHAR(64) NOT NULL,
    "scoring_model_version"         VARCHAR(64) NOT NULL,
    "differentiation_status"        VARCHAR(64) NOT NULL,
    "required_skills"               TEXT NOT NULL,
    "recommended_candidate_id"      BIGINT,
    "candidate_count"               INTEGER NOT NULL,
    "request_source"                VARCHAR(64) NOT NULL,
    "fit_weight"                    DOUBLE PRECISION NOT NULL,
    "load_weight"                   DOUBLE PRECISION NOT NULL,
    "performance_weight"            DOUBLE PRECISION NOT NULL,
    "normalization_contract"        VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_recommendation_snapshots_project_created"
    ON "recommendation_snapshots" ("project_id", "created_at");

CREATE TABLE IF NOT EXISTS "recommendation_snapshot_candidates" (
    "id"                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "snapshot_id"                VARCHAR(64) NOT NULL,
    "candidate_id"               BIGINT NOT NULL,
    "rank"                       INTEGER NOT NULL,
    "ranking_key"                BIGINT NOT NULL,
    "full_precision_score"       DOUBLE PRECISION NOT NULL,
    "ranking_raw_fit"            DOUBLE PRECISION NOT NULL,
    "presentation_fit_value"     DOUBLE PRECISION,
    "fit_status"                 VARCHAR(32) NOT NULL,
    "stored_workload_value"      INTEGER,
    "workload_status"            VARCHAR(32) NOT NULL,
    "derived_performance_input"  DOUBLE PRECISION NOT NULL,
    "performance_status"         VARCHAR(32) NOT NULL,
    "member_status"              VARCHAR(32) NOT NULL,
    "selected_as_recommendation" BOOLEAN NOT NULL,
    CONSTRAINT "fk_snapshot_candidates_snapshot" FOREIGN KEY ("snapshot_id")
        REFERENCES "recommendation_snapshots" ("snapshot_id") ON DELETE CASCADE,
    CONSTRAINT "uq_snapshot_candidates_snapshot_rank" UNIQUE ("snapshot_id", "rank")
);

CREATE INDEX IF NOT EXISTS "idx_recommendation_snapshot_candidates_snapshot_id"
    ON "recommendation_snapshot_candidates" ("snapshot_id");
