CREATE TABLE password_reset_tokens (
   id BIGSERIAL PRIMARY KEY,
   token VARCHAR(255) NOT NULL UNIQUE,
   expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
   is_used BOOLEAN NOT NULL DEFAULT FALSE,
   user_id BIGINT NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE,
   CONSTRAINT fk_user_password_reset_token FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);