package com.taskpilot.ai.rag.service;

import com.taskpilot.ai.rag.config.RagEmbeddingProperties;
import com.taskpilot.ai.rag.domain.ClaimedDocumentJob;
import com.taskpilot.ai.rag.domain.DocumentChunk;
import com.taskpilot.ai.rag.domain.DocumentStatus;
import com.taskpilot.ai.rag.repository.JdbcDocumentChunkRepository;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.PlatformTransactionManager;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;

import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
class DocumentJobConcurrencyIntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("pgvector/pgvector:pg16")
            .withDatabaseName("taskpilot_test")
            .withUsername("test")
            .withPassword("test");

    private static JdbcTemplate jdbcTemplate;
    private static PlatformTransactionManager transactionManager;
    private static DocumentJobClaimer claimer;
    private static JdbcDocumentChunkRepository chunkRepository;
    private static DocumentIngestionServiceImpl ingestionService;

    @BeforeAll
    static void initDb() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.postgresql.Driver");
        dataSource.setUrl(postgres.getJdbcUrl());
        dataSource.setUsername(postgres.getUsername());
        dataSource.setPassword(postgres.getPassword());

        jdbcTemplate = new JdbcTemplate(dataSource);
        transactionManager = new DataSourceTransactionManager(dataSource);
        claimer = new DocumentJobClaimer(jdbcTemplate);
        chunkRepository = new JdbcDocumentChunkRepository(jdbcTemplate);

        RagEmbeddingProperties properties = new RagEmbeddingProperties(12, 2, 100, 10, 5, 3000L);
        ingestionService = new DocumentIngestionServiceImpl(
                null, chunkRepository, null, null, null, null, properties, jdbcTemplate, transactionManager
        );

        // Schema setup
        jdbcTemplate.execute("CREATE EXTENSION IF NOT EXISTS vector;");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id BIGINT NOT NULL,
                storage_key VARCHAR(512) NOT NULL,
                original_filename VARCHAR(255) NOT NULL,
                content_type VARCHAR(100),
                file_size BIGINT,
                status VARCHAR(32) NOT NULL DEFAULT 'UPLOADING',
                processing_version INT NOT NULL DEFAULT 0,
                lease_until TIMESTAMP WITH TIME ZONE,
                retry_count INT NOT NULL DEFAULT 0,
                next_attempt_at TIMESTAMP WITH TIME ZONE,
                error_message TEXT,
                created_by BIGINT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
        """);

        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS document_chunks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                document_id BIGINT NOT NULL,
                project_id BIGINT NOT NULL,
                chunk_index INT NOT NULL,
                content TEXT NOT NULL,
                embedding vector(768) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            );
        """);

        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS idx_documents_queue_claim
            ON documents (status, next_attempt_at, lease_until, created_at ASC)
            WHERE status IN ('QUEUED', 'RETRY_WAIT', 'PROCESSING');
        """);
    }

    @BeforeEach
    void cleanData() {
        jdbcTemplate.execute("DELETE FROM document_chunks;");
        jdbcTemplate.execute("DELETE FROM documents;");
    }

    @Test
    @DisplayName("TEST 1 — Concurrent Claim: 1 QUEUED document claimed by 3 concurrent workers -> exactly 1 receives it, v=1, status=PROCESSING")
    void testConcurrentClaimSingleJob() throws Exception {
        // GIVEN: 1 document in QUEUED status
        long docId = insertDocument(100L, "doc1.pdf", "QUEUED", 0, null, null);

        int workerCount = 3;
        ExecutorService executor = Executors.newFixedThreadPool(workerCount);
        CountDownLatch startLatch = new CountDownLatch(1);
        List<Future<Optional<ClaimedDocumentJob>>> futures = new ArrayList<>();

        for (int i = 0; i < workerCount; i++) {
            futures.add(executor.submit(() -> {
                startLatch.await();
                return claimer.claimNextJob(10);
            }));
        }

        startLatch.countDown();
        executor.shutdown();
        assertThat(executor.awaitTermination(5, TimeUnit.SECONDS)).isTrue();

        List<ClaimedDocumentJob> claimed = new ArrayList<>();
        for (Future<Optional<ClaimedDocumentJob>> f : futures) {
            f.get().ifPresent(claimed::add);
        }

        // Exactly 1 worker receives the document, other 2 receive empty
        assertThat(claimed).hasSize(1);
        ClaimedDocumentJob job = claimed.get(0);
        assertThat(job.documentId()).isEqualTo(docId);
        assertThat(job.processingVersion()).isEqualTo(1);

        // Verify database state
        Map<String, Object> row = jdbcTemplate.queryForMap(
                "SELECT status, processing_version, lease_until FROM documents WHERE id = ?", docId
        );
        assertThat(row.get("status")).isEqualTo("PROCESSING");
        assertThat(((Number) row.get("processing_version")).intValue()).isEqualTo(1);
        assertThat(row.get("lease_until")).isNotNull();
    }

    @Test
    @DisplayName("TEST 2 — Multiple Jobs Concurrent Claim: 3 QUEUED documents claimed by 3 workers -> each gets disjoint document (FOR UPDATE SKIP LOCKED)")
    void testMultipleJobsConcurrentClaim() throws Exception {
        // GIVEN: 3 documents QUEUED
        long idA = insertDocument(100L, "A.pdf", "QUEUED", 0, null, null);
        long idB = insertDocument(100L, "B.pdf", "QUEUED", 0, null, null);
        long idC = insertDocument(100L, "C.pdf", "QUEUED", 0, null, null);

        int workerCount = 3;
        ExecutorService executor = Executors.newFixedThreadPool(workerCount);
        CountDownLatch startLatch = new CountDownLatch(1);
        List<Future<Optional<ClaimedDocumentJob>>> futures = new ArrayList<>();

        for (int i = 0; i < workerCount; i++) {
            futures.add(executor.submit(() -> {
                startLatch.await();
                return claimer.claimNextJob(10);
            }));
        }

        startLatch.countDown();
        executor.shutdown();
        assertThat(executor.awaitTermination(5, TimeUnit.SECONDS)).isTrue();

        Set<Long> claimedDocIds = new HashSet<>();
        for (Future<Optional<ClaimedDocumentJob>> f : futures) {
            f.get().ifPresent(job -> claimedDocIds.add(job.documentId()));
        }

        // All 3 distinct documents claimed without duplicates
        assertThat(claimedDocIds).containsExactlyInAnyOrder(idA, idB, idC);
    }

    @Test
    @DisplayName("TEST 3 — Zombie Finalize Rejection: Worker A (v1) finalization is rejected after Worker B claims v2 and finalizes chunks")
    void testZombieFinalizeRejection() {
        // GIVEN: Worker A claims doc (v1)
        long docId = insertDocument(100L, "spec.pdf", "QUEUED", 0, null, null);
        ClaimedDocumentJob claimA = claimer.claimNextJob(10).orElseThrow();
        assertThat(claimA.processingVersion()).isEqualTo(1);

        // Simulate lease expiration
        jdbcTemplate.update("UPDATE documents SET lease_until = NOW() - INTERVAL '1 minute' WHERE id = ?", docId);

        // Worker B re-claims the document (v2)
        ClaimedDocumentJob claimB = claimer.claimNextJob(10).orElseThrow();
        assertThat(claimB.processingVersion()).isEqualTo(2);

        // Worker B finishes ingestion, writes Worker B chunks, marks READY
        float[] vectorB = new float[768];
        vectorB[0] = 0.99f;
        DocumentChunk chunkB = new DocumentChunk(null, docId, 100L, 0, "Content by Worker B", vectorB, Instant.now());
        boolean finalizeB = ingestionService.finalizeFencedSuccess(docId, 2, List.of(chunkB));
        assertThat(finalizeB).isTrue();

        // Verify document is READY and contains Worker B chunk
        Map<String, Object> stateAfterB = jdbcTemplate.queryForMap("SELECT status, processing_version FROM documents WHERE id = ?", docId);
        assertThat(stateAfterB.get("status")).isEqualTo("READY");
        assertThat(((Number) stateAfterB.get("processing_version")).intValue()).isEqualTo(2);
        assertThat(chunkRepository.countByDocumentId(docId)).isEqualTo(1);
        assertThat(chunkRepository.findByDocumentId(docId).get(0).content()).isEqualTo("Content by Worker B");

        // WHEN: Stale Worker A attempts to finalize using v1
        float[] vectorA = new float[768];
        vectorA[0] = 0.11f;
        DocumentChunk chunkA = new DocumentChunk(null, docId, 100L, 0, "Stale Content by Worker A", vectorA, Instant.now());
        boolean finalizeA = ingestionService.finalizeFencedSuccess(docId, 1, List.of(chunkA));

        // THEN: Worker A finalization must be REJECTED
        assertThat(finalizeA).as("Stale worker A finalization must be rejected").isFalse();

        // Worker B chunks and READY status remain completely untouched!
        Map<String, Object> stateAfterA = jdbcTemplate.queryForMap("SELECT status, processing_version FROM documents WHERE id = ?", docId);
        assertThat(stateAfterA.get("status")).isEqualTo("READY");
        assertThat(((Number) stateAfterA.get("processing_version")).intValue()).isEqualTo(2);
        List<DocumentChunk> chunksInDb = chunkRepository.findByDocumentId(docId);
        assertThat(chunksInDb).hasSize(1);
        assertThat(chunksInDb.get(0).content()).isEqualTo("Content by Worker B");
    }

    @Test
    @DisplayName("TEST 4 — Zombie Failure Rejection: Worker A (v1) markFailed is rejected when document has advanced to v2")
    void testZombieFailureRejection() {
        // GIVEN: Worker A claims v1
        long docId = insertDocument(100L, "notes.pdf", "QUEUED", 0, null, null);
        ClaimedDocumentJob claimA = claimer.claimNextJob(10).orElseThrow();
        assertThat(claimA.processingVersion()).isEqualTo(1);

        // Lease expires, Worker B claims v2
        jdbcTemplate.update("UPDATE documents SET lease_until = NOW() - INTERVAL '1 minute' WHERE id = ?", docId);
        ClaimedDocumentJob claimB = claimer.claimNextJob(10).orElseThrow();
        assertThat(claimB.processingVersion()).isEqualTo(2);

        // WHEN: Stale Worker A attempts to record failure for v1
        ingestionService.handleIngestionFailure(docId, 1, 0, new RuntimeException("Worker A network timeout"));

        // THEN: Worker B's state is untouched: status remains PROCESSING and version remains 2
        Map<String, Object> row = jdbcTemplate.queryForMap(
                "SELECT status, processing_version, error_message FROM documents WHERE id = ?", docId
        );
        assertThat(row.get("status")).isEqualTo("PROCESSING");
        assertThat(((Number) row.get("processing_version")).intValue()).isEqualTo(2);
        assertThat(row.get("error_message")).isNull();
    }

    @Test
    @DisplayName("TEST 8 — Retry Wait Is Not Claimed Early: RETRY_WAIT is not claimable before next_attempt_at, but claimable after")
    void testRetryWaitNotClaimedEarly() {
        // GIVEN: Document in RETRY_WAIT with next_attempt_at in the future (+1 hour)
        long docId = insertDocument(100L, "retry.pdf", "RETRY_WAIT", 1, null, "NOW() + INTERVAL '1 hour'");

        // WHEN: Claiming jobs
        Optional<ClaimedDocumentJob> earlyClaim = claimer.claimNextJob(10);

        // THEN: Not eligible yet
        assertThat(earlyClaim).isEmpty();

        // Fast-forward time past next_attempt_at
        jdbcTemplate.update("UPDATE documents SET next_attempt_at = NOW() - INTERVAL '1 second' WHERE id = ?", docId);

        // WHEN: Claiming again
        Optional<ClaimedDocumentJob> readyClaim = claimer.claimNextJob(10);

        // THEN: Successfully claimed, version incremented
        assertThat(readyClaim).isPresent();
        assertThat(readyClaim.get().documentId()).isEqualTo(docId);
        assertThat(readyClaim.get().processingVersion()).isEqualTo(2);
    }

    @Test
    @DisplayName("TEST 9 — Expired Lease Reclaim: PROCESSING document with expired lease is reclaimed with incremented version")
    void testExpiredLeaseReclaimed() {
        // GIVEN: Document in PROCESSING with expired lease_until
        long docId = insertDocument(100L, "stuck.pdf", "PROCESSING", 1, "NOW() - INTERVAL '5 minutes'", null);

        // WHEN: Claiming jobs
        Optional<ClaimedDocumentJob> reclaimed = claimer.claimNextJob(10);

        // THEN: Expired lease reclaimed, processing_version incremented to 2
        assertThat(reclaimed).isPresent();
        assertThat(reclaimed.get().documentId()).isEqualTo(docId);
        assertThat(reclaimed.get().processingVersion()).isEqualTo(2);

        Map<String, Object> row = jdbcTemplate.queryForMap(
                "SELECT status, processing_version, lease_until FROM documents WHERE id = ?", docId
        );
        assertThat(row.get("status")).isEqualTo("PROCESSING");
        assertThat(((Number) row.get("processing_version")).intValue()).isEqualTo(2);
        assertThat(row.get("lease_until")).isNotNull();
    }

    private long insertDocument(Long projectId, String filename, String status, int version, String leaseUntilSql, String nextAttemptSql) {
        String sql = String.format("""
            INSERT INTO documents (project_id, storage_key, original_filename, content_type, file_size, status, processing_version, lease_until, next_attempt_at)
            VALUES (?, ?, ?, 'application/pdf', 1024, ?, ?, %s, %s)
            RETURNING id;
            """,
            leaseUntilSql != null ? leaseUntilSql : "NULL",
            nextAttemptSql != null ? nextAttemptSql : "NULL"
        );

        return jdbcTemplate.queryForObject(
                sql,
                Long.class,
                projectId,
                "storage/" + filename,
                filename,
                status,
                version
        );
    }
}
